apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: langfuse
type: Opaque
stringData:
  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_PASSWORD: clickhouse
  CLICKHOUSE_DB: langfuse
